config/routes.rb
Rails.application.routes.draw do
  
  get 'articles/show'
  get 'articles' => 'articles#index'

  get 'faq/:slug' => 'faqs#category'
  get 'faq' => 'faqs#index'
  get 'pages/:slug' => 'pages#show'
  get 'categories/:slug' => 'categories#show'
	get 'articles/search' => 'articles#search'
  get 'articles/:slug' => 'articles#show'
  get 'articles' => 'articles#index'
  get 'photo_albums/:slug' => 'photo_albums#show'
  get 'photo_albums' => 'photo_albums#index'
  
  resources :comments
  resources :pictures
  resources :votes
  
  namespace :account do
    post 'pictures/upload'
    resources :pictures
    resources :locations do
      member do
        get 'primary' => 'locations#primary'
      end
    end
  end
  
  namespace :admin do
    
    namespace :cms do
      resources :articles do
        member do
          get 'pictures' 
          get 'categories' 
          post 'categories' => 'articles#create_categories'
        end
      end
      resources :pages
      resources :lists
      resources :content_blocks
      resources :menus
      resources :menu_items
      resources :regions
      resources :locations do
        member do
          get 'pictures'
          get 'categories'
          get 'extra_properties'
          get 'formatted'
          post 'categories' => 'locations#create_categories'
        end
      end
      resources :photo_albums do
        member do
          get 'pictures' => 'photo_albums#pictures'
        end
      end
      resources :pictures do
        member do
         get 'moveup' => 'pictures#moveup'
         get 'movedown' => 'pictures#movedown'
        end
      end
      resources :comments
      resources :votes
      resources :filemanager
      resources :faqs
    end
    
  end
  
end

app/models/article.rb
# == Schema Information
#
# Table name: cms_articles
#
#  id             :integer          not null, primary key
#  allow_comments :boolean          default(FALSE), not null
#  allow_pings    :boolean          default(FALSE), not null
#  author         :string(255)      not null
#  body           :text(65535)      not null
#  excerpt        :text(65535)
#  keywords       :string(255)
#  published_at   :date
#  slug           :string(255)      not null
#  status         :string(255)      not null
#  title          :string(255)      not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  domain_id      :integer          not null
#  user_id        :integer
#
# Indexes
#
#  index_cms_articles_on_domain_id  (domain_id)
#  index_cms_articles_on_user_id    (user_id)
#

class Article < ActiveRecord::Base
  include Exportable
  acts_as_taggable_on :tags
  self.table_name = "cms_articles"


  belongs_to :user
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :pictures, -> { order :sort }, as: :imageable
  has_many :comments, as: :commentable
  has_many :article_categories
  has_many :categories, -> { order :sort }, through: :article_categories

  validates_presence_of :title, :author, :excerpt, :body, :slug
  validates_uniqueness_of :slug

  def cache_key
    "article:#{domain_id}:#{slug}"
  end

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end

end

app/controllers/account/locations_controller.rb
class Account::LocationsController < Account::BaseController

  def index
    @locations = Location.where(user_id: session[:user_id]).order('created_at DESC')
  end

  def new
    @location = Location.new name: 'New location'
    render 'edit'
  end

  def create
    @location = Location.new(location_params)
    @location.slug = SecureRandom.hex(5)
    @location.user_id = current_user.id
    @location.hidden = true

    if @location.save
      Location.where("user_id = ? AND id != ?", session[:user_id], @location.id).update_all(default: false) if @location.default
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def edit
    @location = Location.find_by(id: params[:id], user_id: session[:user_id])
  end

  def update
    @location = Location.find_by(id: params[:id], user_id: session[:user_id])

    if @location.update(location_params)
      Location.where("user_id = ? AND id != ?", session[:user_id], @location.id).update_all(default: false) if @location.default
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @location = Location.find_by(id: params[:id], user_id: session[:user_id])
    @location.destroy
    redirect_to action: 'index'
  end


  def primary
    Location.where(user_id: session[:user_id]).update_all(default: false)
    Location.where(user_id: session[:user_id], id: params[:id]).update_all(default: true)

    return redirect_back(fallback_location: account_root_path)
  end


  private

  def location_params
    params.require(:location).permit(:default, :name, :street1, :street2, :city, :state, :zip, :country, :contact_person, :phone)
  end

end

app/controllers/admin/cms/articles_controller.rb
class Admin::Cms::ArticlesController < Admin::BaseController

  def index
    authorize Article.new

    @articles = Article.where(domain_id: cookies[:domain_id]).order(published_at: :desc)
    @articles = @articles.where("title LIKE '%#{params[:q]}%'") unless params[:q].nil?

    respond_to do |format|
      format.html { @articles = @articles.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Article.to_csv(@articles) }
    end
  end

  def new
    @article = authorize Article.new(title: 'New article', status: "draft")
    render 'edit'
  end

  def create
    @article = authorize Article.new(article_params)
    @article.domain_id = cookies[:domain_id]

    if @article.save
      redirect_to action: 'show', id: @article.id, notice: 'Article was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @article = authorize Article.find(params[:id])
  end

  def edit
    @article = authorize Article.find(params[:id])
  end

  def update
    @article = authorize Article.find(params[:id])

    if @article.update(article_params)
      Rails.cache.delete @article
      redirect_to action: 'show', id: @article.id, notice: 'Article was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @article = authorize Article.find(params[:id])
    @article.destroy

    Rails.cache.delete @article
    redirect_to action: 'index', notice: 'Article has been deleted.'
  end


  def pictures
    @article = Article.find(params[:id])
    authorize @article, :show?
    Rails.cache.delete @article
  end

  def categories
    @article = Article.includes(:categories).find(params[:id])
    authorize @article, :show?
  end

  def create_categories
    authorize Article, :update?

    ArticleCategory.delete_all article_id: params[:id]
    category_ids = params[:category_ids]

    category_ids.each do |id|
      ArticleCategory.create article_id: params[:id], category_id: id
    end

    Rails.cache.delete @article
    redirect_to action: 'show', id: params[:id], notice: 'Article was successfully updated.'
  end


  private

  def article_params
    params.require(:article).permit!
  end


end

app/controllers/admin/cms/comments_controller.rb
class Admin::Cms::CommentsController < Admin::BaseController

  def index
    authorize Comment.new
    @comments = Comment.order(created_at: :desc)

    respond_to do |format|
      format.html { @comments = @comments.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Comment.to_csv(@comments) }
    end
  end

  def new
    @comment = authorize Menu.new
    render 'edit'
  end

  def create
    @comment = authorize Comment.new(comment_params)
    @comment.assign_attributes(
        ip_address: request.ip,
        user_agent: request.user_agent,
        author: current_user.name,
        email: current_user.email,
        user_id: current_user.id)

    # check whether this is spam
    Akismet.api_key = Cache.setting(Rails.configuration.domain_id, :cms, "Akismet API Key")
    Akismet.app_url = Cache.setting(Rails.configuration.domain_id, :system, "Website URL")

    params = {
        type: 'comment',
        text: @comment.content,
        created_at: DateTime.now,
        author: @comment.author,
        author_email: @comment.email,
        post_url: request.url,
        referrer: request.referrer
    }

    @comment.spam = Akismet.spam?(request.ip, request.user_agent, params)
    if @comment.spam
      flash[:notice] = "Your comment will be posted after it is approved."
      @comment.approved = false
    end

    @comment.save
    redirect_to action: "index"
  end


  def edit
    @comment = authorize Comment.find(params[:id])
  end

  def update
    @comment = authorize Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @comment = authorize Comment.find(params[:id])
    @comment.destroy

    flash[:notice] = 'Comment has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def comment_params
    params.require(:comment).permit!
  end

end

app/controllers/admin/cms/content_blocks_controller.rb
class Admin::Cms::ContentBlocksController < Admin::BaseController

  def index
    authorize ContentBlock.new
    @content_blocks = ContentBlock.where(domain_id: cookies[:domain_id]).order(:key)

    respond_to do |format|
      format.html { @content_blocks = @content_blocks.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data ContentBlock.to_csv(@content_blocks) }
    end
  end

  def new
    @content_block = authorize ContentBlock.new(key: 'new-block')
    render 'edit'
  end

  def create
    @content_block = authorize ContentBlock.new(content_block_params)
    @content_block.domain_id = cookies[:domain_id]

    if @content_block.save
      redirect_to action: 'index', notice: 'ContentBlock was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @content_block = authorize ContentBlock.find(params[:id])
  end

  def edit
    @content_block = authorize ContentBlock.find(params[:id])
  end

  def update
    @content_block = authorize ContentBlock.find(params[:id])

    if @content_block.update(content_block_params)
      Rails.cache.delete @content_block
      redirect_to action: 'index', notice: 'Content Block was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @content_block = authorize ContentBlock.find(params[:id])
    @content_block.destroy

    Rails.cache.delete @content_block
    flash[:notice] = 'Content Block has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def content_block_params
    params.require(:content_block).permit(:key, :content)
  end

end

app/controllers/admin/cms/faqs_controller.rb
class Admin::Cms::FaqsController < Admin::BaseController

  def index
    authorize Faq.new
    @faqs = Faq.where(domain_id: cookies[:domain_id]).order(:sort)

    respond_to do |format|
      format.html { @faqs = @faqs.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Faq.to_csv(@faqs) }
    end
  end

  def new
    @faq = authorize Faq.new
    render 'edit'
  end

  def create
    @faq = authorize Faq.new(faq_params)
    @faq.domain_id = cookies[:domain_id]

    if @faq.save
      redirect_to action: 'index', notice: 'Faq was successfully created.'
    else
      render 'edit'
    end
  end

  def edit
    @faq = authorize Faq.find(params[:id])
  end

  def update
    @faq = authorize Faq.find(params[:id])

    if @faq.update(faq_params)
      Rails.cache.delete @faq
      redirect_to action: 'index', notice: 'Faq was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @faq = authorize Faq.find(params[:id])
    @faq.destroy

    Rails.cache.delete @faq
    flash[:notice] = 'Faq has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def faq_params
    params.require(:faq).permit!
  end

end

app/controllers/admin/cms/filemanager_controller.rb
class Admin::Cms::FilemanagerController < Admin::BaseController
  def index
  end
end

app/controllers/admin/cms/lists_controller.rb
class Admin::Cms::ListsController < Admin::BaseController

  def index
    authorize List.new
    @lists = List.includes(:items).order("user_id, affiliate_id, name").paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @list = authorize List.new
    add_items(@list, 5)

    render 'edit'
  end

  def create
    @list = authorize List.new(list_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @list.items.length + 5
      count.times { @list.items.build(priority: 1) }
      return render 'edit'
    end

    if @list.save
      redirect_to action: 'index', notice: 'List was successfully created.'
    else
      add_items(@list, 5)
      render 'edit'
    end
  end

  def edit
    @list = authorize List.find(params[:id])
    add_items(@list, 5)
  end

  def update
    @list = authorize List.find(params[:id])
    item_count = @list.items.length

    @list.assign_attributes(list_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      add_items(@list, count)

      return render 'edit'
    end

    if @list.save
      redirect_to action: 'index', notice: 'List was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @list = authorize List.find(params[:id])
    @list.destroy

    flash[:success] = 'List has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def list_params
    params.require(:list).permit!
  end

  def add_items(list, count)
    max_item = list.items.max_by(&:priority)
    priority = max_item ? max_item.priority : 0

    count.times do
      priority += 1
      list.items.build(priority: priority)
    end
  end

end

app/controllers/admin/cms/locations_controller.rb
class Admin::Cms::LocationsController < Admin::BaseController

  def index
    authorize Location.new

    @locations = Location.order('name')
    @locations = @locations.where("name LIKE '%#{params[:q]}%'") unless params[:q].nil?

    unless params[:c].blank?
      @category = Category.find_by(slug: params[:c], entity_type: :location)
      @locations = @locations.joins(:location_categories).where("cms_location_categories.category_id = ?", @category.id)
    end

    respond_to do |format|
      format.html { @locations = @locations.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Location.to_csv(@locations) }
    end
  end

  def new
    @location = authorize Location.new(name: 'New location')
    render 'edit'
  end

  def create
    @location = authorize Location.new(location_params)

    if @location.save
      redirect_to action: 'show', id: @location.id, notice: 'Location was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @location = authorize Location.find(params[:id])
  end

  def edit
    @location = authorize Location.find(params[:id])
  end

  def update
    @location = authorize Location.find(params[:id])

    if @location.update(location_params)
      redirect_to action: 'show', id: @location.id, notice: 'Location was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @location = authorize Location.find(params[:id])
    @location.destroy
    redirect_to action: 'index', notice: 'Location has been deleted.'
  end


  def pictures
    @location = Location.find(params[:id])
    authorize @location, :show?
  end

  def categories
    @location = Location.includes(:categories).find(params[:id])
    authorize @location, :show?
  end

  def create_categories
    authorize Location, :update?

    LocationCategory.delete_all location_id: params[:id]
    category_ids = params[:category_ids]

    category_ids.each do |id|
      LocationCategory.create location_id: params[:id], category_id: id
    end

    redirect_to action: 'show', id: params[:id], notice: 'Location was successfully updated.'
  end

  def extra_properties
    @location = Location.find(params[:id])
    authorize @location, :show?
    5.times { @location.extra_properties.build }
  end

  def formatted
    @location = Location.find(params[:id])
    render text: @location.to_text
  end


  private

  def location_params
    params.require(:location).permit!
  end

end

app/controllers/admin/cms/menu_items_controller.rb
class Admin::Cms::MenuItemsController < Admin::BaseController

  def new
    @menu_item = MenuItem.new title: 'New menu item', menu_id: params[:menu_id]
    render 'edit'
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      Rails.cache.delete @menu_item.menu
      redirect_to admin_cms_menus_path
    else
      render 'edit'
    end
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    @menu_item = MenuItem.find(params[:id])

    if @menu_item.update(menu_item_params)
      Rails.cache.delete @menu_item.menu
      redirect_to admin_cms_menus_path
    else
      render 'edit'
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])

    Rails.cache.delete @menu_item.menu
    @menu_item.destroy

    redirect_to admin_cms_menus_path
  end


  private

  def menu_item_params
    params.require(:menu_item).permit(:menu_id, :title, :link_url, :sort, :enabled)
  end
end

app/helpers/admin/cms/articles_helper.rb
module Admin::Cms::ArticlesHelper

  def article_status(article)
    h = {
        "published" => "success",
        "removed" => "important",
        "pending" => "warning",
        "draft" => "info"
    }

    "<span class='label label-#{h[article.status]}'>#{article.status}</span>".html_safe
  end

end

app/views/admin/cms/locations/attributes.html.erb
<h2><i class="fa fa-map-marker"></i>&nbsp; <%= @location.name %></h2>

<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_cms_location_path(@location) %></li>
  <li><%= link_to "Pictures", pictures_admin_cms_location_path(@location) %></a></li>
  <li><%= link_to "Categories", categories_admin_cms_location_path(@location) %></li>
  <li class="active"><a href="#">Attributes</a></li>
  <li><%= link_to "Sublocations", sublocations_admin_cms_location_path(@location) %></li>
</ul>


<form action="/admin/cms/locations/<%= params[:id] %>/attributes" method="post" class="form-inline simple_form">
	<%= token_tag %>
	<input type="hidden" name="id" value="<%= params[:id] %>">

	<% all_attributes = Attribute.where(entity_type: :location).order(:sort) %>
	<% all_attributes.each do |attr| 
		loc_attr = @location.location_attributes.find { |pa| pa.attribute_id == attr.id } 
		loc_attr = LocationAttribute.new if loc_attr.nil? %>
	<div class="control-group">
		<label class="control-label" for="<%= attr.name %>"><%= attr.name %></label>
		<div class="controls">
			<% if attr.data_type == 'text' %>
			<textarea class="col-md-5 text" rows="4" name="attr-<%= attr.id %>"><%= loc_attr %></textarea>
			<% elsif attr.data_type == 'numeric' %>
			<input type="number" class="col-md-2 string" name="attr-<%= attr.id %>" value="<%= loc_attr %>" />
			<% elsif attr.data_type == 'boolean' %>
			<input type="checkbox" class="check" name="attr-<%= attr.id %>" value="on" <%= 'checked' if loc_attr.value == 'on' %> />
			<% elsif attr.data_type == 'selection' %>
			<select name="attr-<%= attr.id %>">
				<% attr.metadata.split('|').each do |opt| %>
				<option <%= 'selected' if opt == loc_attr.value %>><%= opt %></option>
				<% end %>
			</select>
			<% end %>
			 &nbsp; <i>(<%= attr.notes %>)</i>
		</div>
	</div>
	<%end%>

	<div class="form-actions">
		<button class="btn btn-primary">Update</button>
	</div>
</form>



<% content_for :title do %>
    Locations: <%= @location.name%>
<% end %>


<% content_for :breadcrumbs do %>
	<li><a href="#">Web Content</a></li>
	<li><%= link_to "Locations", admin_cms_locations_path %></li>
	<li><%= link_to @location.name, admin_cms_location_path(@location)%> </li>
	<li class="active">edit</li>
<% end %>

app/views/admin/cms/locations/categories.html.erb
<style>
    form ul {
        list-style-type: none;
    }

    form li {
        margin: 10px;
        padding-top: 5px;
    }

    form li input {
        position: relative;
        top: -4px;
    }
</style>

<h2><i class="fa fa-map-marker"></i>&nbsp; <%= @location.name %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_cms_location_path(@location) %></li>
  <li><%= link_to "Pictures", pictures_admin_cms_location_path(@location) %></a></li>
  <li class="active"><a href="#">Categories</a></li>
  <li><%= link_to "Extra Properties", extra_properties_admin_cms_location_path(@location) %></li>
</ul>

<br/>

<form action="/admin/cms/locations/<%= params[:id] %>/categories" method="post" class="categories">
  <%= token_tag %>
  <input type="hidden" name="id" value="<%= params[:id] %>">
  <% categories = Category.where(entity_type: :location).load
     pcats = @location.categories
     top_levels = categories.select { |c| c.parent_id == nil } %>
  <ul>
    <% top_levels.each do |cat|
      children = categories.select { |c| c.parent_id == cat.id } %>
      <li>
        <input type="checkbox" name="category_ids[]" value="<%= cat.id %>" <%= "checked='checked'" if pcats.include?(cat) %>/> &nbsp; <%= cat.name %>
        <ul>
          <% children.each do |child| %>
            <li>
              <input type="checkbox" name="category_ids[]" value="<%= child.id %>" <%= "checked='checked'" if pcats.include?(child) %>/> &nbsp; <%= child.name %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
  <div class="form-actions">
    <button class="btn btn-primary">Update</button>
  </div>
</form>



<% content_for :title do %>
  Locations: <%= @location.name %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Locations", admin_cms_locations_path %></li>
  <li><%= link_to @location.name, admin_cms_location_path(@location) %> </li>
  <li class="active">edit</li>
<% end %>

app/views/admin/cms/locations/edit.html.erb
<h2><i class="fa fa-map-marker"></i>&nbsp; <%= @location.name %></h2>

<% unless @location.id.nil? %>
  <ul class="nav nav-tabs" style="margin-bottom: 20px;">
    <li class="active"><a href="#">Summary</a></li>
    <li><%= link_to "Pictures", pictures_admin_cms_location_path(@location) %></a></li>
    <li><%= link_to "Extra Properties", extra_properties_admin_cms_location_path(@location) %></li>
  </ul>
<% end %>

<%= simple_form_for [:admin, :cms, @location], class: "my-form" do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>

  <%= f.input :name %>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :contact_person %>
      <%= f.input :street1 %>
      <%= f.input :street2 %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :zip %>
      <%= f.input :country %>
      <%= f.input :phone %>
      <%= f.input :fax %>
    </div>
    <div class="col-md-6">
      <%= f.association :user %>
      <%= f.association :affiliate %>
      <%= f.input :email %>
      <%= f.input :website %>
      <%= f.input :slug %>
      <%= f.input :hidden %>
      <%= f.input :latitude %>
      <%= f.input :longitude %>
    </div>
  </div>

  <%= f.input :tag_list, as: :tags %>
  <%= f.input :summary, as: :text, input_html: {rows: 3} %>
  <%= ckeditor_input(@location, "description") %>

  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>



<% content_for :title do %>
  Locations: <%= @location.name %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Locations", admin_cms_locations_path %></li>
  <% if @location.persisted? %>
    <li><%= link_to @location.name, admin_cms_location_path(@location) %></li>
    <li class="active">edit</li>
  <% else %>
    <li><%= @location.name %>
  <% end %>
<% end %>

app/views/admin/cms/locations/extra_properties.html.erb
<h2><i class="fa fa-map-marker"></i>&nbsp; <%= @location.name %></h2>

<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_cms_location_path(@location) %></li>
  <li><%= link_to "Pictures", pictures_admin_cms_location_path(@location) %></a></li>
  <li class="active"><a href="#">Extra Properties</a></li>
</ul>


<%= render 'admin/shared/extra_properties_list', object: @location, redirect: admin_cms_location_path(@location) %>



<% content_for :title do %>
  Locations: <%= @location.name %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Locations", admin_cms_locations_path %></li>
  <li><%= link_to @location.name, admin_cms_location_path(@location) %> </li>
  <li class="active">edit</li>
<% end %>

app/views/admin/cms/locations/index.html.erb
<div class="pull-right">
  <select id="selAction" class="form-control">
    <option> - - Select Action - -</option>
    <option method="get" value="<%= new_admin_cms_location_path(c: params[:c]) %>">New Location</option>
    <option method="get" value="<%= admin_system_categories_path(type: :location) %>">Setup Categories</option>
    <optgroup label="Show location in category: ">
      <option method="get" value="<%= admin_cms_locations_path %>">All categories</option>
      <% Category.where(entity_type: :location).each do |c| %>
        <option method="get" value="<%= admin_cms_locations_path(c: c.slug) %>"><%= c.name %></option>
      <% end %>
    </optgroup>
  </select>
</div>


<h2><i class="fa fa-location-arrow"></i>&nbsp; <%= @category.nil? ? "Locations" : @category.name %></h2>

<%= render "admin/shared/search_results_header", object: @locations %>

<%= will_paginate @locations %>
<table class="table table-striped table-condensed">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>&nbsp;</th>
  </tr>
  <% @locations.each do |loc| %>
    <tr>
      <td><%= loc.id %></td>
      <td><%= link_to loc.name, admin_cms_location_path(loc) %></td>
      <td><%= loc.to_text(new_line: ", ", skip_country: true) %></td>
      <td><%= loc.phone %></td>
      <td>
        <%= link_to "edit", edit_admin_cms_location_path(loc) %> &nbsp;
        <%= link_to "delete",
                    {action: "destroy", id: loc.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @locations %>



<% content_for :title do %>
  Locations
<% end %>



<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li class="active">Locations</li>
<% end %>


<% content_for :head do %>

  <script type="text/javascript">
      $(document).ready(function () {

          $("#selAction").change(function () {
              window.location = $("#selAction").val();
          });

      });
  </script>

<% end %>

app/views/admin/cms/locations/pictures.html.erb
<h2><i class="fa fa-map-marker"></i>&nbsp; <%= @location.name %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_cms_location_path(@location) %></li>
  <li class="active"><a href="#">Pictures</a></li>
  <li><%= link_to "Extra Properties", extra_properties_admin_cms_location_path(@location) %></li>
</ul>

<br>
<%= render partial: 'admin/shared/image_list', locals: {object: @location} %>



<% content_for :title do %>
  Locations: <%= @location.name %>
<% end %>



<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Locations", admin_cms_locations_path %></li>
  <li><%= link_to @location.name, admin_cms_location_path(@location) %> </li>
  <li class="active">edit</li>
<% end %>