config/routes.rb
Rails.application.routes.draw do
  
  get 'articles/show'
  get 'articles' => 'articles#index'

  get 'faq/:slug' => 'faqs#category'
  get 'faq' => 'faqs#index'
  get 'pages/:slug' => 'pages#show'
  get 'categories/:slug' => 'categories#show'
	get 'articles/search' => 'articles#search'
  get 'articles/:slug' => 'articles#show'
  get 'articles' => 'articles#index'
  get 'photo_albums/:slug' => 'photo_albums#show'
  get 'photo_albums' => 'photo_albums#index'
  
  resources :comments
  resources :pictures
  resources :votes
  
  namespace :account do
    post 'pictures/upload'
    resources :pictures
    resources :locations do
      member do
        get 'primary' => 'locations#primary'
      end
    end
  end
  
  namespace :admin do
    
    namespace :cms do
      resources :articles do
        member do
          get 'pictures' 
          get 'categories' 
          post 'categories' => 'articles#create_categories'
        end
      end
      resources :pages
      resources :lists
      resources :content_blocks
      resources :menus
      resources :menu_items
      resources :regions
      resources :locations do
        member do
          get 'pictures'
          get 'categories'
          get 'extra_properties'
          get 'formatted'
          post 'categories' => 'locations#create_categories'
        end
      end
      resources :photo_albums do
        member do
          get 'pictures' => 'photo_albums#pictures'
        end
      end
      resources :pictures do
        member do
         get 'moveup' => 'pictures#moveup'
         get 'movedown' => 'pictures#movedown'
        end
      end
      resources :comments
      resources :votes
      resources :filemanager
      resources :faqs
    end
    
  end
  
end

app/models/article.rb
# == Schema Information
#
# Table name: cms_articles
#
#  id             :integer          not null, primary key
#  allow_comments :boolean          default(FALSE), not null
#  allow_pings    :boolean          default(FALSE), not null
#  author         :string(255)      not null
#  body           :text(65535)      not null
#  excerpt        :text(65535)
#  keywords       :string(255)
#  published_at   :date
#  slug           :string(255)      not null
#  status         :string(255)      not null
#  title          :string(255)      not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  domain_id      :integer          not null
#  user_id        :integer
#
# Indexes
#
#  index_cms_articles_on_domain_id  (domain_id)
#  index_cms_articles_on_user_id    (user_id)
#

class Article < ActiveRecord::Base
  include Exportable
  acts_as_taggable_on :tags
  self.table_name = "cms_articles"


  belongs_to :user
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :pictures, -> { order :sort }, as: :imageable
  has_many :comments, as: :commentable
  has_many :article_categories
  has_many :categories, -> { order :sort }, through: :article_categories

  validates_presence_of :title, :author, :excerpt, :body, :slug
  validates_uniqueness_of :slug

  def cache_key
    "article:#{domain_id}:#{slug}"
  end

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end

end

app/controllers/admin/cms/articles_controller.rb
class Admin::Cms::ArticlesController < Admin::BaseController

  def index
    authorize Article.new

    @articles = Article.where(domain_id: cookies[:domain_id]).order(published_at: :desc)
    @articles = @articles.where("title LIKE '%#{params[:q]}%'") unless params[:q].nil?

    respond_to do |format|
      format.html { @articles = @articles.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Article.to_csv(@articles) }
    end
  end

  def new
    @article = authorize Article.new(title: 'New article', status: "draft")
    render 'edit'
  end

  def create
    @article = authorize Article.new(article_params)
    @article.domain_id = cookies[:domain_id]

    if @article.save
      redirect_to action: 'show', id: @article.id, notice: 'Article was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @article = authorize Article.find(params[:id])
  end

  def edit
    @article = authorize Article.find(params[:id])
  end

  def update
    @article = authorize Article.find(params[:id])

    if @article.update(article_params)
      Rails.cache.delete @article
      redirect_to action: 'show', id: @article.id, notice: 'Article was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @article = authorize Article.find(params[:id])
    @article.destroy

    Rails.cache.delete @article
    redirect_to action: 'index', notice: 'Article has been deleted.'
  end


  def pictures
    @article = Article.find(params[:id])
    authorize @article, :show?
    Rails.cache.delete @article
  end

  def categories
    @article = Article.includes(:categories).find(params[:id])
    authorize @article, :show?
  end

  def create_categories
    authorize Article, :update?

    ArticleCategory.delete_all article_id: params[:id]
    category_ids = params[:category_ids]

    category_ids.each do |id|
      ArticleCategory.create article_id: params[:id], category_id: id
    end

    Rails.cache.delete @article
    redirect_to action: 'show', id: params[:id], notice: 'Article was successfully updated.'
  end


  private

  def article_params
    params.require(:article).permit!
  end


end

app/controllers/admin/cms/comments_controller.rb
class Admin::Cms::CommentsController < Admin::BaseController

  def index
    authorize Comment.new
    @comments = Comment.order(created_at: :desc)

    respond_to do |format|
      format.html { @comments = @comments.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Comment.to_csv(@comments) }
    end
  end

  def new
    @comment = authorize Menu.new
    render 'edit'
  end

  def create
    @comment = authorize Comment.new(comment_params)
    @comment.assign_attributes(
        ip_address: request.ip,
        user_agent: request.user_agent,
        author: current_user.name,
        email: current_user.email,
        user_id: current_user.id)

    # check whether this is spam
    Akismet.api_key = Cache.setting(Rails.configuration.domain_id, :cms, "Akismet API Key")
    Akismet.app_url = Cache.setting(Rails.configuration.domain_id, :system, "Website URL")

    params = {
        type: 'comment',
        text: @comment.content,
        created_at: DateTime.now,
        author: @comment.author,
        author_email: @comment.email,
        post_url: request.url,
        referrer: request.referrer
    }

    @comment.spam = Akismet.spam?(request.ip, request.user_agent, params)
    if @comment.spam
      flash[:notice] = "Your comment will be posted after it is approved."
      @comment.approved = false
    end

    @comment.save
    redirect_to action: "index"
  end


  def edit
    @comment = authorize Comment.find(params[:id])
  end

  def update
    @comment = authorize Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @comment = authorize Comment.find(params[:id])
    @comment.destroy

    flash[:notice] = 'Comment has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def comment_params
    params.require(:comment).permit!
  end

end

app/controllers/admin/cms/content_blocks_controller.rb
class Admin::Cms::ContentBlocksController < Admin::BaseController

  def index
    authorize ContentBlock.new
    @content_blocks = ContentBlock.where(domain_id: cookies[:domain_id]).order(:key)

    respond_to do |format|
      format.html { @content_blocks = @content_blocks.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data ContentBlock.to_csv(@content_blocks) }
    end
  end

  def new
    @content_block = authorize ContentBlock.new(key: 'new-block')
    render 'edit'
  end

  def create
    @content_block = authorize ContentBlock.new(content_block_params)
    @content_block.domain_id = cookies[:domain_id]

    if @content_block.save
      redirect_to action: 'index', notice: 'ContentBlock was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @content_block = authorize ContentBlock.find(params[:id])
  end

  def edit
    @content_block = authorize ContentBlock.find(params[:id])
  end

  def update
    @content_block = authorize ContentBlock.find(params[:id])

    if @content_block.update(content_block_params)
      Rails.cache.delete @content_block
      redirect_to action: 'index', notice: 'Content Block was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @content_block = authorize ContentBlock.find(params[:id])
    @content_block.destroy

    Rails.cache.delete @content_block
    flash[:notice] = 'Content Block has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def content_block_params
    params.require(:content_block).permit(:key, :content)
  end

end

app/controllers/admin/cms/faqs_controller.rb
class Admin::Cms::FaqsController < Admin::BaseController

  def index
    authorize Faq.new
    @faqs = Faq.where(domain_id: cookies[:domain_id]).order(:sort)

    respond_to do |format|
      format.html { @faqs = @faqs.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Faq.to_csv(@faqs) }
    end
  end

  def new
    @faq = authorize Faq.new
    render 'edit'
  end

  def create
    @faq = authorize Faq.new(faq_params)
    @faq.domain_id = cookies[:domain_id]

    if @faq.save
      redirect_to action: 'index', notice: 'Faq was successfully created.'
    else
      render 'edit'
    end
  end

  def edit
    @faq = authorize Faq.find(params[:id])
  end

  def update
    @faq = authorize Faq.find(params[:id])

    if @faq.update(faq_params)
      Rails.cache.delete @faq
      redirect_to action: 'index', notice: 'Faq was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @faq = authorize Faq.find(params[:id])
    @faq.destroy

    Rails.cache.delete @faq
    flash[:notice] = 'Faq has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def faq_params
    params.require(:faq).permit!
  end

end

app/controllers/admin/cms/filemanager_controller.rb
class Admin::Cms::FilemanagerController < Admin::BaseController
  def index
  end
end

app/controllers/admin/cms/lists_controller.rb
class Admin::Cms::ListsController < Admin::BaseController

  def index
    authorize List.new
    @lists = List.includes(:items).order("user_id, affiliate_id, name").paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @list = authorize List.new
    add_items(@list, 5)

    render 'edit'
  end

  def create
    @list = authorize List.new(list_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @list.items.length + 5
      count.times { @list.items.build(priority: 1) }
      return render 'edit'
    end

    if @list.save
      redirect_to action: 'index', notice: 'List was successfully created.'
    else
      add_items(@list, 5)
      render 'edit'
    end
  end

  def edit
    @list = authorize List.find(params[:id])
    add_items(@list, 5)
  end

  def update
    @list = authorize List.find(params[:id])
    item_count = @list.items.length

    @list.assign_attributes(list_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      add_items(@list, count)

      return render 'edit'
    end

    if @list.save
      redirect_to action: 'index', notice: 'List was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @list = authorize List.find(params[:id])
    @list.destroy

    flash[:success] = 'List has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def list_params
    params.require(:list).permit!
  end

  def add_items(list, count)
    max_item = list.items.max_by(&:priority)
    priority = max_item ? max_item.priority : 0

    count.times do
      priority += 1
      list.items.build(priority: priority)
    end
  end

end

app/controllers/admin/cms/locations_controller.rb
class Admin::Cms::LocationsController < Admin::BaseController

  def index
    authorize Location.new

    @locations = Location.order('name')
    @locations = @locations.where("name LIKE '%#{params[:q]}%'") unless params[:q].nil?

    unless params[:c].blank?
      @category = Category.find_by(slug: params[:c], entity_type: :location)
      @locations = @locations.joins(:location_categories).where("cms_location_categories.category_id = ?", @category.id)
    end

    respond_to do |format|
      format.html { @locations = @locations.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Location.to_csv(@locations) }
    end
  end

  def new
    @location = authorize Location.new(name: 'New location')
    render 'edit'
  end

  def create
    @location = authorize Location.new(location_params)

    if @location.save
      redirect_to action: 'show', id: @location.id, notice: 'Location was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @location = authorize Location.find(params[:id])
  end

  def edit
    @location = authorize Location.find(params[:id])
  end

  def update
    @location = authorize Location.find(params[:id])

    if @location.update(location_params)
      redirect_to action: 'show', id: @location.id, notice: 'Location was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @location = authorize Location.find(params[:id])
    @location.destroy
    redirect_to action: 'index', notice: 'Location has been deleted.'
  end


  def pictures
    @location = Location.find(params[:id])
    authorize @location, :show?
  end

  def categories
    @location = Location.includes(:categories).find(params[:id])
    authorize @location, :show?
  end

  def create_categories
    authorize Location, :update?

    LocationCategory.delete_all location_id: params[:id]
    category_ids = params[:category_ids]

    category_ids.each do |id|
      LocationCategory.create location_id: params[:id], category_id: id
    end

    redirect_to action: 'show', id: params[:id], notice: 'Location was successfully updated.'
  end

  def extra_properties
    @location = Location.find(params[:id])
    authorize @location, :show?
    5.times { @location.extra_properties.build }
  end

  def formatted
    @location = Location.find(params[:id])
    render text: @location.to_text
  end


  private

  def location_params
    params.require(:location).permit!
  end

end

app/controllers/admin/cms/menu_items_controller.rb
class Admin::Cms::MenuItemsController < Admin::BaseController

  def new
    @menu_item = MenuItem.new title: 'New menu item', menu_id: params[:menu_id]
    render 'edit'
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      Rails.cache.delete @menu_item.menu
      redirect_to admin_cms_menus_path
    else
      render 'edit'
    end
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    @menu_item = MenuItem.find(params[:id])

    if @menu_item.update(menu_item_params)
      Rails.cache.delete @menu_item.menu
      redirect_to admin_cms_menus_path
    else
      render 'edit'
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])

    Rails.cache.delete @menu_item.menu
    @menu_item.destroy

    redirect_to admin_cms_menus_path
  end


  private

  def menu_item_params
    params.require(:menu_item).permit(:menu_id, :title, :link_url, :sort, :enabled)
  end
end

app/controllers/admin/cms/menus_controller.rb
class Admin::Cms::MenusController < Admin::BaseController

  def index
    authorize Menu.new
    @menus = Menu.where(domain_id: cookies[:domain_id]).all
  end

  def new
    @menu = authorize Menu.new(title: 'New menu')
    render 'edit'
  end

  def create
    @menu = authorize Menu.new(menu_params)
    @menu.domain_id = cookies[:domain_id]

    if @menu.save
      redirect_to action: 'index', notice: 'Menu was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @menu = authorize Menu.find(params[:id])
  end

  def edit
    @menu = authorize Menu.find(params[:id])
  end

  def update
    @menu = authorize Menu.find(params[:id])

    if @menu.update(menu_params)
      Rails.cache.delete @menu
      redirect_to action: 'index', notice: 'Menu was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @menu = authorize Menu.find(params[:id])
    @menu.destroy

    Rails.cache.delete @menu
    flash[:notice] = "Menu has been deleted."
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def menu_params
    params.require(:menu).permit(:title, :key, :css_class, :notes)
  end

end

app/controllers/admin/cms/votes_controller.rb
class Admin::Cms::VotesController < Admin::BaseController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/admin/cms/articles_helper.rb
module Admin::Cms::ArticlesHelper

  def article_status(article)
    h = {
        "published" => "success",
        "removed" => "important",
        "pending" => "warning",
        "draft" => "info"
    }

    "<span class='label label-#{h[article.status]}'>#{article.status}</span>".html_safe
  end

end

app/views/admin/cms/articles/categories.html.erb
<style>
    form ul {
        list-style-type: none;
    }

    form li {
        margin: 10px;
        padding-top: 5px;
    }

    form li input {
        position: relative;
        top: -4px;
    }
</style>

<h2><i class="fa fa-edit"></i>&nbsp; <%= @article.title %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_cms_article_path(@article) %></li>
  <li><%= link_to "Pictures", pictures_admin_cms_article_path(@article) %></a></li>
  <li class="active"><a href="#">Categories</a></li>
</ul>

<br/>

<form action="/admin/cms/locations/<%= params[:id] %>/categories" method="post" class="categories">
  <%= token_tag %>
  <input type="hidden" name="id" value="<%= params[:id] %>">
  <% categories = Category.where(entity_type: :article).load
     pcats = @article.categories
     top_levels = categories.select { |c| c.parent_id == nil } %>
  <ul>
    <% top_levels.each do |cat|
      children = categories.select { |c| c.parent_id == cat.id } %>
      <li>
        <input type="checkbox" name="category_ids[]" value="<%= cat.id %>" <%= "checked='checked'" if pcats.include?(cat) %>/> &nbsp; <%= cat.name %>
        <ul>
          <% children.each do |child| %>
            <li>
              <input type="checkbox" name="category_ids[]" value="<%= child.id %>" <%= "checked='checked'" if pcats.include?(child) %>/> &nbsp; <%= child.name %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
  <div class="form-actions">
    <button class="btn btn-primary">Update</button>
  </div>
</form>



<% content_for :title do %>
  Articles: <%= @article.title %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Articles", admin_cms_articles_path %></li>
  <li><%= link_to @article.title, admin_cms_article_path(@article) %> </li>
  <li class="active">edit</li>
<% end %>

app/views/admin/cms/articles/edit.html.erb
<style>
    .form-inline .control-label {
        width: 80px;
    }
</style>
<h2><i class="fa fa-edit"></i>&nbsp; <%= @article.title %></h2>

<% if @article.persisted? %>
  <ul class="nav nav-tabs" style="margin-bottom: 20px;">
    <li class="active"><a href="#">Summary</a></li>
    <li><%= link_to "Pictures", pictures_admin_cms_article_path(@article) %></a></li>
    <li><%= link_to "Categories", categories_admin_cms_article_path(@article) %></li>
  </ul>
<% end %>

<%= simple_form_for [:admin, :cms, @article] do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>

  <div class="row">

    <div class="col-md-8">
      <%= f.input :title %>
      <%= f.input :author %>
      <%= f.association :user %>
      <%= f.input :published_at, as: :datepicker %>
      <%= f.input :slug %>
      <%= f.input :keywords %>
      <%= f.input :tag_list, as: :tags %>
      <%= f.input :excerpt %>
    </div>

    <div class="col-md-4">
      <div class="panel panel-default options-panel">
        <div class="panel-heading">Options</div>
        <div class="panel-body">
          <b>Status: </b> &nbsp;
          <%= f.input_field :status, collection: ["draft", "pending", "published", "removed"] %><br><br>


          <%= f.input_field :allow_comments %> Allow comments <br>
          <%= f.input_field :allow_pings %> Allow pings <br><br>
        </div>
      </div>
    </div>
  </div>

  <hr/>

  <b>Body</b><br>
  <%= ckeditor_input_field(@article, "body") %>

  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>


<% content_for :title do %>
  Articles: <%= @article.title %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Articles", admin_cms_articles_path %></li>
  <% if @article.persisted? %>
    <li><%= link_to @article.title, admin_cms_article_path(@article) %></li>
    <li class="active">edit</li>
  <% else %>
    <li><%= @article.title %>
  <% end %>
<% end %>

app/views/admin/cms/articles/index.html.erb
<h2>
  <div class="pull-right">
    <%= link_to new_admin_cms_article_path, class: 'btn btn-sm btn-default' do %>
      <i class="fa fa-plus"></i> New article
    <% end %>
    <%= link_to admin_system_categories_path(type: :article), class: 'btn btn-sm btn-default' do %>
      <i class="fa fa-list-ul"></i> Setup categories
    <% end %>
  </div>
  <i class="fa fa-edit"></i>&nbsp; Articles
</h2>

<%= render "admin/shared/search_results_header", object: @articles %>

<%= will_paginate @articles %>
<table class="table table-striped table-condensed">
  <tr>
    <th>ID</th>
    <th>Publish Date</th>
    <th>Title</th>
    <th>Author</th>
    <th>Status</th>
    <th>&nbsp;</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.published_at.nil? ? "- pending -" : systime(article.published_at) %></td>
      <td><%= link_to article.title, admin_cms_article_path(article) %></td>
      <td><%= article.author %></td>
      <td><%= article_status(article) %></td>
      <td>
        <%= link_to "edit", edit_admin_cms_article_path(article) %> &nbsp;
        <%= link_to "delete",
                    {action: "destroy", id: article.id},
                    method: :delete,
                    data: {confirm: "Are you sure?"} %>
      </td>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @articles %>




<% content_for :title do %>
  Articles
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li class="active">Articles</li>
<% end %>

app/views/admin/cms/articles/pictures.html.erb
<h2><i class="fa fa-map-marker"></i>&nbsp; <%= @article.title %></h2>


<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_cms_article_path(@article) %></li>
  <li class="active"><a href="#">Pictures</a></li>
  <li><%= link_to "Categories", categories_admin_cms_article_path(@article) %></a></li>
</ul>


<%= render partial: 'admin/shared/image_list', locals: {object: @article} %>


<% content_for :title do %>
  Articles: <%= @article.title %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Articles", admin_cms_articles_path %></li>
  <li><%= link_to @article.title, admin_cms_article_path(@article) %> </li>
  <li class="active">edit</li>
<% end %>

app/views/admin/cms/articles/show.html.erb
<style>
    .rendered-html img {
        max-width: 100%;
    }
</style>

<div class="pull-right">
  <a href="/articles/<%= @article.slug %>" class="btn btn-sm btn-default">view</a>
  <%= link_to "edit", edit_admin_cms_article_path(@article), class: "btn btn-sm btn-default" %>
</div>


<h2><i class="fa fa-edit"></i>&nbsp; <%= @article.title %></h2>
<%= tag_list @article %>
<hr>

<div class="row-fluid">
  <div class="col-md-8" style="padding-bottom: 30px;">

    <h4>Excerpt</h4>
    <blockquote><%= @article.excerpt %></blockquote>

    <h4>Body</h4>
    <div class="rendered-html">
      <%= @article.body.html_safe %>
    </div>
  </div>


  <div class="col-md-4">
    <table class="table summary table-condensed">
      <tr>
        <td>Status</td>
        <td><%= article_status(@article) %></td>
      </tr>
      <% unless @article.published_at.nil? %>
        <tr>
          <td>Published</td>
          <td><%= sysdate @article.published_at %></td>
        </tr>
      <% end %>
      <tr>
        <td>Author</td>
        <td><%= @article.author %></td>
      </tr>
      <tr>
        <td>Allow Comments</td>
        <td><%= @article.allow_comments ? "yes" : "no" %></td>
      </tr>
      <tr>
        <td>Allow Pings</td>
        <td><%= @article.allow_pings ? "yes" : "no" %></td>
      </tr>
      <% unless @article.keywords.blank? %>
        <tr>
          <td>Keywords</td>
          <td><%= @article.keywords %></td>
        </tr>
      <% end %>
    </table>

    <h4>Pictures</h4>
    <% if @article.pictures.length > 0 %>
      <a href="<%= cdn_image_url @article.pictures[0], 800, 700, 0 %>" data-lightbox="image-1">
        <img src="<%= cdn_image_url @article.pictures[0], 400, 300, 2 %>" class="img-responsive" title="<%= @article.pictures[0].caption %>"/>
      </a>
    <% end %>

    <% if @article.pictures.length > 1 %>
      <br/>
      <% @article.pictures[1..-1].each do |pic| %>
        <a href="<%= cdn_image_url pic, 700, 600, 0 %>" data-lightbox="image-1">
          <img src="<%= cdn_image_url pic, 60, 60, 2 %>" class="img-thumbnail" style="margin: 4px" title="<%= pic.caption %>"/>
        </a>
      <% end %>
    <% end %>

    <hr/>
  </div>

</div> <!-- row-fluid -->



<% content_for :title do %>
  Articles: <%= @article.title %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to "Articles", admin_cms_articles_path %></li>
  <li class="active"><%= @article.title %></li>
<% end %>