config/routes.rb
Rails.application.routes.draw do
  
  get 'articles/show'
  get 'articles' => 'articles#index'

  get 'faq/:slug' => 'faqs#category'
  get 'faq' => 'faqs#index'
  get 'pages/:slug' => 'pages#show'
  get 'categories/:slug' => 'categories#show'
	get 'articles/search' => 'articles#search'
  get 'articles/:slug' => 'articles#show'
  get 'articles' => 'articles#index'
  get 'photo_albums/:slug' => 'photo_albums#show'
  get 'photo_albums' => 'photo_albums#index'
  
  resources :comments
  resources :pictures
  resources :votes
  
  namespace :account do
    post 'pictures/upload'
    resources :pictures
    resources :locations do
      member do
        get 'primary' => 'locations#primary'
      end
    end
  end
  
  namespace :admin do
    
    namespace :cms do
      resources :articles do
        member do
          get 'pictures' 
          get 'categories' 
          post 'categories' => 'articles#create_categories'
        end
      end
      resources :pages
      resources :lists
      resources :content_blocks
      resources :menus
      resources :menu_items
      resources :regions
      resources :locations do
        member do
          get 'pictures'
          get 'categories'
          get 'extra_properties'
          get 'formatted'
          post 'categories' => 'locations#create_categories'
        end
      end
      resources :photo_albums do
        member do
          get 'pictures' => 'photo_albums#pictures'
        end
      end
      resources :pictures do
        member do
         get 'moveup' => 'pictures#moveup'
         get 'movedown' => 'pictures#movedown'
        end
      end
      resources :comments
      resources :votes
      resources :filemanager
      resources :faqs
    end
    
  end
  
end

app/controllers/account/pictures_controller.rb
class Account::PicturesController < Account::BaseController
  skip_before_action :verify_authenticity_token, only: :upload, raise: false

  def index
    @pictures = Picture.where(user_id: session[:user_id]).order(created_at: :desc).paginate(page: params[:page], per_page: @per_page)
    @picture = Picture.new(imageable_type: "photoalbum")
  end


  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = session[:user_id]
    base_dir = Cache.setting(Rails.configuration.domain_id, :system, "Static Files Path")
    @picture.set_picture_properties(base_dir)

    if @picture.save
      flash[:success] = "Photo was successfully uploaded."
    else
      flash[:error] = @picture.errors.full_messages.join(". ")
    end

    @pictures = Picture.where(user_id: session[:user_id]).order(created_at: :desc).paginate(page: params[:page], per_page: @per_page)
    render "index"
  end

  def destroy
    Picture.find_by(id: params[:id], user_id: session[:user_id]).destroy
    redirect_back(fallback_location: account_root_path)
  end


  # called from DropZone.js
  def upload
    static_files_path = Cache.setting(Rails.configuration.domain_id, :system, "Static Files Path")
    user_dir = static_files_path + "/userfiles/uploads/#{session[:user_id]}"
    #user_dir = "/tmp"
    Dir.mkdir(user_dir) unless File.exist?(user_dir)

    uploaded_io = params[:file]
    ext = uploaded_io.original_filename.split('.').last

    unless uploaded_io.nil? || ['jpg', 'gif'].include?(ext) == false
      file_path = user_dir + '/' + SecureRandom.hex(6) + '.' + ext

      File.open(file_path, 'wb') do |file|
        file.write(uploaded_io.read)
      end

      return render json: {status: 'ok', file_path: file_path.sub(static_files_path, "")}
    end

    render json: {status: 'error', message: "Not a valid image file"}
  end


  private

  def picture_params
    params.require(:picture).permit(:caption, :file_path, :data1, :data2, :approved, :imageable_type, :imageable_id)
  end

end

app/controllers/admin/cms/articles_controller.rb
class Admin::Cms::ArticlesController < Admin::BaseController

  def index
    authorize Article.new

    @articles = Article.where(domain_id: cookies[:domain_id]).order(published_at: :desc)
    @articles = @articles.where("title LIKE '%#{params[:q]}%'") unless params[:q].nil?

    respond_to do |format|
      format.html { @articles = @articles.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Article.to_csv(@articles) }
    end
  end

  def new
    @article = authorize Article.new(title: 'New article', status: "draft")
    render 'edit'
  end

  def create
    @article = authorize Article.new(article_params)
    @article.domain_id = cookies[:domain_id]

    if @article.save
      redirect_to action: 'show', id: @article.id, notice: 'Article was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @article = authorize Article.find(params[:id])
  end

  def edit
    @article = authorize Article.find(params[:id])
  end

  def update
    @article = authorize Article.find(params[:id])

    if @article.update(article_params)
      Rails.cache.delete @article
      redirect_to action: 'show', id: @article.id, notice: 'Article was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @article = authorize Article.find(params[:id])
    @article.destroy

    Rails.cache.delete @article
    redirect_to action: 'index', notice: 'Article has been deleted.'
  end


  def pictures
    @article = Article.find(params[:id])
    authorize @article, :show?
    Rails.cache.delete @article
  end

  def categories
    @article = Article.includes(:categories).find(params[:id])
    authorize @article, :show?
  end

  def create_categories
    authorize Article, :update?

    ArticleCategory.delete_all article_id: params[:id]
    category_ids = params[:category_ids]

    category_ids.each do |id|
      ArticleCategory.create article_id: params[:id], category_id: id
    end

    Rails.cache.delete @article
    redirect_to action: 'show', id: params[:id], notice: 'Article was successfully updated.'
  end


  private

  def article_params
    params.require(:article).permit!
  end


end

app/controllers/admin/cms/comments_controller.rb
class Admin::Cms::CommentsController < Admin::BaseController

  def index
    authorize Comment.new
    @comments = Comment.order(created_at: :desc)

    respond_to do |format|
      format.html { @comments = @comments.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Comment.to_csv(@comments) }
    end
  end

  def new
    @comment = authorize Menu.new
    render 'edit'
  end

  def create
    @comment = authorize Comment.new(comment_params)
    @comment.assign_attributes(
        ip_address: request.ip,
        user_agent: request.user_agent,
        author: current_user.name,
        email: current_user.email,
        user_id: current_user.id)

    # check whether this is spam
    Akismet.api_key = Cache.setting(Rails.configuration.domain_id, :cms, "Akismet API Key")
    Akismet.app_url = Cache.setting(Rails.configuration.domain_id, :system, "Website URL")

    params = {
        type: 'comment',
        text: @comment.content,
        created_at: DateTime.now,
        author: @comment.author,
        author_email: @comment.email,
        post_url: request.url,
        referrer: request.referrer
    }

    @comment.spam = Akismet.spam?(request.ip, request.user_agent, params)
    if @comment.spam
      flash[:notice] = "Your comment will be posted after it is approved."
      @comment.approved = false
    end

    @comment.save
    redirect_to action: "index"
  end


  def edit
    @comment = authorize Comment.find(params[:id])
  end

  def update
    @comment = authorize Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @comment = authorize Comment.find(params[:id])
    @comment.destroy

    flash[:notice] = 'Comment has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def comment_params
    params.require(:comment).permit!
  end

end

app/controllers/admin/cms/content_blocks_controller.rb
class Admin::Cms::ContentBlocksController < Admin::BaseController

  def index
    authorize ContentBlock.new
    @content_blocks = ContentBlock.where(domain_id: cookies[:domain_id]).order(:key)

    respond_to do |format|
      format.html { @content_blocks = @content_blocks.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data ContentBlock.to_csv(@content_blocks) }
    end
  end

  def new
    @content_block = authorize ContentBlock.new(key: 'new-block')
    render 'edit'
  end

  def create
    @content_block = authorize ContentBlock.new(content_block_params)
    @content_block.domain_id = cookies[:domain_id]

    if @content_block.save
      redirect_to action: 'index', notice: 'ContentBlock was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @content_block = authorize ContentBlock.find(params[:id])
  end

  def edit
    @content_block = authorize ContentBlock.find(params[:id])
  end

  def update
    @content_block = authorize ContentBlock.find(params[:id])

    if @content_block.update(content_block_params)
      Rails.cache.delete @content_block
      redirect_to action: 'index', notice: 'Content Block was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @content_block = authorize ContentBlock.find(params[:id])
    @content_block.destroy

    Rails.cache.delete @content_block
    flash[:notice] = 'Content Block has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def content_block_params
    params.require(:content_block).permit(:key, :content)
  end

end

app/controllers/admin/cms/faqs_controller.rb
class Admin::Cms::FaqsController < Admin::BaseController

  def index
    authorize Faq.new
    @faqs = Faq.where(domain_id: cookies[:domain_id]).order(:sort)

    respond_to do |format|
      format.html { @faqs = @faqs.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Faq.to_csv(@faqs) }
    end
  end

  def new
    @faq = authorize Faq.new
    render 'edit'
  end

  def create
    @faq = authorize Faq.new(faq_params)
    @faq.domain_id = cookies[:domain_id]

    if @faq.save
      redirect_to action: 'index', notice: 'Faq was successfully created.'
    else
      render 'edit'
    end
  end

  def edit
    @faq = authorize Faq.find(params[:id])
  end

  def update
    @faq = authorize Faq.find(params[:id])

    if @faq.update(faq_params)
      Rails.cache.delete @faq
      redirect_to action: 'index', notice: 'Faq was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @faq = authorize Faq.find(params[:id])
    @faq.destroy

    Rails.cache.delete @faq
    flash[:notice] = 'Faq has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def faq_params
    params.require(:faq).permit!
  end

end

app/controllers/admin/cms/filemanager_controller.rb
class Admin::Cms::FilemanagerController < Admin::BaseController
  def index
  end
end

app/controllers/admin/cms/lists_controller.rb
class Admin::Cms::ListsController < Admin::BaseController

  def index
    authorize List.new
    @lists = List.includes(:items).order("user_id, affiliate_id, name").paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @list = authorize List.new
    add_items(@list, 5)

    render 'edit'
  end

  def create
    @list = authorize List.new(list_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - @list.items.length + 5
      count.times { @list.items.build(priority: 1) }
      return render 'edit'
    end

    if @list.save
      redirect_to action: 'index', notice: 'List was successfully created.'
    else
      add_items(@list, 5)
      render 'edit'
    end
  end

  def edit
    @list = authorize List.find(params[:id])
    add_items(@list, 5)
  end

  def update
    @list = authorize List.find(params[:id])
    item_count = @list.items.length

    @list.assign_attributes(list_params)

    unless params[:add_more_items].blank?
      count = params[:add_more_items].to_i - item_count + 5
      add_items(@list, count)

      return render 'edit'
    end

    if @list.save
      redirect_to action: 'index', notice: 'List was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @list = authorize List.find(params[:id])
    @list.destroy

    flash[:success] = 'List has been deleted.'
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def list_params
    params.require(:list).permit!
  end

  def add_items(list, count)
    max_item = list.items.max_by(&:priority)
    priority = max_item ? max_item.priority : 0

    count.times do
      priority += 1
      list.items.build(priority: priority)
    end
  end

end

app/controllers/admin/cms/locations_controller.rb
class Admin::Cms::LocationsController < Admin::BaseController

  def index
    authorize Location.new

    @locations = Location.order('name')
    @locations = @locations.where("name LIKE '%#{params[:q]}%'") unless params[:q].nil?

    unless params[:c].blank?
      @category = Category.find_by(slug: params[:c], entity_type: :location)
      @locations = @locations.joins(:location_categories).where("cms_location_categories.category_id = ?", @category.id)
    end

    respond_to do |format|
      format.html { @locations = @locations.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Location.to_csv(@locations) }
    end
  end

  def new
    @location = authorize Location.new(name: 'New location')
    render 'edit'
  end

  def create
    @location = authorize Location.new(location_params)

    if @location.save
      redirect_to action: 'show', id: @location.id, notice: 'Location was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @location = authorize Location.find(params[:id])
  end

  def edit
    @location = authorize Location.find(params[:id])
  end

  def update
    @location = authorize Location.find(params[:id])

    if @location.update(location_params)
      redirect_to action: 'show', id: @location.id, notice: 'Location was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @location = authorize Location.find(params[:id])
    @location.destroy
    redirect_to action: 'index', notice: 'Location has been deleted.'
  end


  def pictures
    @location = Location.find(params[:id])
    authorize @location, :show?
  end

  def categories
    @location = Location.includes(:categories).find(params[:id])
    authorize @location, :show?
  end

  def create_categories
    authorize Location, :update?

    LocationCategory.delete_all location_id: params[:id]
    category_ids = params[:category_ids]

    category_ids.each do |id|
      LocationCategory.create location_id: params[:id], category_id: id
    end

    redirect_to action: 'show', id: params[:id], notice: 'Location was successfully updated.'
  end

  def extra_properties
    @location = Location.find(params[:id])
    authorize @location, :show?
    5.times { @location.extra_properties.build }
  end

  def formatted
    @location = Location.find(params[:id])
    render text: @location.to_text
  end


  private

  def location_params
    params.require(:location).permit!
  end

end

app/controllers/admin/cms/menu_items_controller.rb
class Admin::Cms::MenuItemsController < Admin::BaseController

  def new
    @menu_item = MenuItem.new title: 'New menu item', menu_id: params[:menu_id]
    render 'edit'
  end

  def create
    @menu_item = MenuItem.new(menu_item_params)

    if @menu_item.save
      Rails.cache.delete @menu_item.menu
      redirect_to admin_cms_menus_path
    else
      render 'edit'
    end
  end

  def edit
    @menu_item = MenuItem.find(params[:id])
  end

  def update
    @menu_item = MenuItem.find(params[:id])

    if @menu_item.update(menu_item_params)
      Rails.cache.delete @menu_item.menu
      redirect_to admin_cms_menus_path
    else
      render 'edit'
    end
  end

  def destroy
    @menu_item = MenuItem.find(params[:id])

    Rails.cache.delete @menu_item.menu
    @menu_item.destroy

    redirect_to admin_cms_menus_path
  end


  private

  def menu_item_params
    params.require(:menu_item).permit(:menu_id, :title, :link_url, :sort, :enabled)
  end
end

app/controllers/admin/cms/votes_controller.rb
class Admin::Cms::VotesController < Admin::BaseController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  layout "single_column"

  def new
    @picture = Picture.new
  end

  def show
    @picture = Picture.find_by(id: params[:id], approved: true)
    @photo_album = PhotoAlbum.find(@picture.imageable_id)

    @next = Picture.where("created_at < ?", @picture.created_at).where(approved: true, imageable_type: :photoalbum, imageable_id: @photo_album.id).order(created_at: :desc).first
    @previous = Picture.where("created_at > ?", @picture.created_at).where(approved: true, imageable_type: :photoalbum, imageable_id: @photo_album.id).order(created_at: :desc).first
  end

end

app/helpers/admin/cms/articles_helper.rb
module Admin::Cms::ArticlesHelper

  def article_status(article)
    h = {
        "published" => "success",
        "removed" => "important",
        "pending" => "warning",
        "draft" => "info"
    }

    "<span class='label label-#{h[article.status]}'>#{article.status}</span>".html_safe
  end

end

app/views/admin/cms/pictures/edit.html.erb
<h2><i class="fa fa-image"></i>&nbsp; <%= "Picture ##{@picture.id}" %></h2>

<% unless @picture.id.nil? %>
  <div class="row">
    <div class="col-md-4">
      <a href="<%= cdn_image_url @picture, 700, 600, 0 %>" data-lightbox="image-1">
        <img class="img-thumbnail" style="width: 100%" src="<%= cdn_image_url @picture, 350, 350, 0 %>" alt="<%= @picture.caption %>"/>
      </a>
    </div>
    <div class="col-md-8">
      <table class="table table-bordered table-condensed summary">
        <tr>
          <td>File size</td>
          <td><%= number_to_human_size @picture.file_size %></td>
        </tr>
        <tr>
          <td>Dimensions</td>
          <td><%= @picture.width %> pixels x <%= @picture.height %> pixels</td>
        </tr>
        <tr>
          <td>Type</td>
          <td><%= @picture.format %> <%= @picture.compression_mode %></td>
        </tr>
        <tr>
          <td>Bits per pixel</td>
          <td><%= @picture.bits_per_pixel || "- unknown -" %></td>
        </tr>
        <tr>
          <td>Chroma Subsampling</td>
          <td><%= @picture.chroma_subsampling.blank? ? "- n/a -" : @picture.chroma_subsampling %></td>
        </tr>
        <tr>
          <td>Uploaded</td>
          <td><%= systime @picture.created_at %></td>
        </tr>
      </table>
    </div>
  </div>
<% end %>


<%= simple_form_for [:admin, :cms, @picture], html: {class: 'form-horizontal', style: "margin-top: 20px;"}, wrapper: :horizontal_form do |f| %>

  <%= render 'admin/shared/error_messages', object: f.object %>

  <%= f.input :imageable_type, as: :hidden %>
  <%= f.input :imageable_id, as: :hidden %>

  <div class="form-group string optional password">
    <label class="string control-label col-sm-3" for="file_path">File Path</label>
    <div class="col-sm-9">
      <input type="text" id="file_path" name="picture[file_path]" value="<%= @picture.file_path %>" class="string form-control"/>
      <input type="button" value="Browse Server" class="btn btn-default btn-sm" onclick="javascript:BrowseServer();">
    </div>
  </div>

  <%= f.association :user %>
  <%= f.input :caption %>
  <%= ckeditor_input(@picture, "description") %>

  <%= f.input :data1 %>
  <%= f.input :data2 %>
  <%= f.input :votes %>
  <%= f.input :sort %>
  <%= f.input :approved %>

  <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>

<% end %>



<% content_for :title do %>
  <%= @picture.caption %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li><%= link_to 'Pictures', admin_cms_pictures_path(imageable_id: @picture.imageable_id, imageable_type: @picture.imageable_type) %></li>
  <li class="active">edit</li>
<% end %>


<% content_for :head do %>
  <% static_url = Cache.setting(Rails.configuration.domain_id, :system, "Static Files Url") %>
  <script>
      function BrowseServer() {
          // You can use the "CKFinder" class to render CKFinder in a page:
          var finder = new CKFinder({connectorPath: '<%= static_url %>/ckfinder/core/connector/php/connector.php'});
          //finder.basePath = '../';	// The path for the installation of CKFinder (default = "/ckfinder/").
          finder.selectActionFunction = SetFileField;
          finder.popup();
      }

      // This is a sample function which is called when a file is selected in CKFinder.
      function SetFileField(fileUrl) {
          document.getElementById('file_path').value = fileUrl.substring(<%= static_url.length + 6 %>);
      }
  </script>
<% end %>

app/views/admin/cms/pictures/index.html.erb
<%= link_to "new photo", new_admin_cms_picture_path(imageable_id: params[:imageable_id], imageable_type: params[:imageable_type]), class: 'btn btn-sm btn-default pull-right' %>

<h2><i class="fa fa-images"></i>&nbsp; <%= @parent || "All Pictures" %></h2>

<%= will_paginate @pictures %>
<div class="row">
  <% @pictures.each do |pic| %>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-6">
      <a href="<%= edit_admin_cms_picture_path(pic) %>">
        <img class="img-thumbnail img-responsive" src="<%= cdn_image_url pic.file_path, 200, 200, 2 %>" style="width: 100%; margin-top: 8px;">
      </a>
    </div>
  <% end %>
</div>

<div style="clear: left; margin-bottom: 20px;"></div>

<%= render 'admin/shared/table_summary', data: @pictures %>


<% content_for :title do %>
  Pictures
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">Web Content</a></li>
  <li class="active">Pictures</li>
<% end %>