config/routes.rb
Rails.application.routes.draw do
  
  get 'articles/show'
  get 'articles' => 'articles#index'

  get 'faq/:slug' => 'faqs#category'
  get 'faq' => 'faqs#index'
  get 'pages/:slug' => 'pages#show'
  get 'categories/:slug' => 'categories#show'
	get 'articles/search' => 'articles#search'
  get 'articles/:slug' => 'articles#show'
  get 'articles' => 'articles#index'
  get 'photo_albums/:slug' => 'photo_albums#show'
  get 'photo_albums' => 'photo_albums#index'
  
  resources :comments
  resources :pictures
  resources :votes
  
  namespace :account do
    post 'pictures/upload'
    resources :pictures
    resources :locations do
      member do
        get 'primary' => 'locations#primary'
      end
    end
  end
  
  namespace :admin do
    
    namespace :cms do
      resources :articles do
        member do
          get 'pictures' 
          get 'categories' 
          post 'categories' => 'articles#create_categories'
        end
      end
      resources :pages
      resources :lists
      resources :content_blocks
      resources :menus
      resources :menu_items
      resources :regions
      resources :locations do
        member do
          get 'pictures'
          get 'categories'
          get 'extra_properties'
          get 'formatted'
          post 'categories' => 'locations#create_categories'
        end
      end
      resources :photo_albums do
        member do
          get 'pictures' => 'photo_albums#pictures'
        end
      end
      resources :pictures do
        member do
         get 'moveup' => 'pictures#moveup'
         get 'movedown' => 'pictures#movedown'
        end
      end
      resources :comments
      resources :votes
      resources :filemanager
      resources :faqs
    end
    
  end
  
end

app/views/admin/shared/_cms_menu.html.erb
<li class="<%= 'active' if request.original_url.include? 'admin/cms' %>">
  <a href="#"><i class="fa fa-globe-africa fa-fw"></i> CMS <span class="fa arrow"></span></a>
  <ul class="nav nav-second-level">
    <% if current_user.has_permission?('Article', 'index') %>
      <li><%= link_to "Articles", admin_cms_articles_path %></li>
    <% end %>
    <% if current_user.has_permission?('Comment', 'index') %>
      <li><%= link_to "Comments", admin_cms_comments_path %></li>
    <% end %>
    <% if current_user.has_permission?('ContentBlock', 'index') %>
      <li><%= link_to "Content Blocks", admin_cms_content_blocks_path %></li>
    <% end %>
    <% if current_user.has_permission?('Faq', 'index') %>
      <li><%= link_to "FAQ", admin_cms_faqs_path %></li>
    <% end %>
    <% if current_user.has_permission?('FileManager', 'index') %>
      <li><%= link_to "File manager", admin_cms_filemanager_index_path %></li>
    <% end %>
    <% if current_user.has_permission?('List', 'index') %>
      <li><%= link_to "Lists", admin_cms_lists_path %></li>
    <% end %>
    <% if current_user.has_permission?('Location', 'index') %>
      <li><%= link_to "Locations", admin_cms_locations_path %></li>
    <% end %>
    <% if current_user.has_permission?('Menu', 'index') %>
      <li><%= link_to "Menus", admin_cms_menus_path %></li>
    <% end %>
    <% if current_user.has_permission?('Page', 'index') %>
      <li><%= link_to "Pages", admin_cms_pages_path %></li>
    <% end %>
    <% if current_user.has_permission?('PhotoAlbum', 'index') %>
      <li><%= link_to "Photo Albums", admin_cms_photo_albums_path %></li>
    <% end %>
    <% if current_user.has_permission?('Picture', 'index') %>
      <li><%= link_to "Pictures", admin_cms_pictures_path %></li>
    <% end %>
    <% if current_user.has_permission?('Vote', 'index') %>
      <li><%= link_to "Votes", admin_cms_votes_path %></li>
    <% end %>
  </ul>
</li>

app/views/admin/shared/_image_list.html.erb
<form action="/admin/cms/pictures" class="well" method="post">
  <div>
    <%= token_tag %>
    <input type="hidden" name="picture[imageable_id]" value="<%= object.id %>"/>
    <input type="hidden" name="picture[imageable_type]" value="<%= object.class.to_s.downcase %>"/>
    <input type="hidden" name="redirect" value="<%= request.fullpath %>">

    <div>
      <input type="text" name="picture[file_path]" placeholder="select a picture" id="imageFile" class="col-md-6"> &nbsp;
      <input type="button" value="Browse Server" class="btn btn-sm btn-primary" onclick="filePopup('imageFile');">
    </div>
    <div style="margin-top: 6px;">
      <input type="text" name="picture[caption]" placeholder="Caption for picture (optional)" class="col-md-5"> &nbsp;
      <select name="picture[purpose]">
        <option>web</option>
        <option>web_background</option>
        <option>print_background</option>
        <option>internal</option>
      </select>
      &nbsp;
      <input type="submit" class="btn btn-sm btn-success" value="Add">
    </div>
  </div>
</form>

<table class="table table-striped table-condensed">
  <tr>
    <th>Picture</th>
    <th>Purpose</th>
    <th>Caption</th>
    <th>Sort</th>
    <th>&nbsp;</th>
  </tr>
  <%
    i = 0
    pictures = object.pictures.order('sort')

    pictures.order('sort').each do |pic|
      i = i + 1 %>
    <tr>
      <td>
        <a href="<%= cdn_image_url pic, 700, 600, 0 %>" data-lightbox="image-1">
          <img class="img-thumbnail" src="<%= cdn_image_url pic, 90, 90, 0 %>"/>
        </a>
      </td>
      <td><%= pic.purpose %></td>
      <td><%= pic.caption %></td>
      <td><%= pic.sort %>:
        <% unless i == 1 %>
          <%= link_to raw('<i class="fa fa-chevron-up"></i>'), moveup_admin_cms_picture_path(pic) %>
        <% end %>
        <% unless i == pictures.length %>
          <%= link_to raw('<i class="fa fa-chevron-down"></i>'), movedown_admin_cms_picture_path(pic) %>
        <% end %>
      </td>
      <td><%= link_to "delete", {action: "destroy", controller: "cms/pictures", id: pic.id}, method: :delete %></td>
  <% end %>
</table>